name: SST workflow
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Installing dependencies
        run: |
          bun install
      - name: Run tests
        run: |
          bun run test
      - name: Run build
        run: |
          bun run build

  DeployApp:
    runs-on: ubuntu-latest
    needs: BuildAndTest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ap-southeast-1
      - name: Installing dependencies
        run: |
          bun install
      - name: Deploy app
        run: |
          bun sst deploy --stage prod
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
